[package]
name = "cb"
version = "0.1.3"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["cargo", "wrap_help", "derive"] }
clipboard-anywhere = "0.2.3"
copypasta-ext = "0.4.4"
